import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiPhone,
  HiChatBubbleLeftRight,
  HiShieldCheck,
  HiKey,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiSpringboot,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiPostgresql,
  SiReact,
  SiTypescript,
  SiGitlab,
  SiPrometheus,
  SiGrafana,
  SiLinux,
  SiNodedotjs,
  SiNestjs,
  SiMongodb,
  SiRedis,
  SiOracle,
  SiKeycloak,
  SiAmazonwebservices,
  SiPython,
  SiGnubash,
  SiSonarqube,
  SiArgo,
  SiIstio,
  SiHelm,
  SiTailwindcss,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaJava,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  phone: HiPhone,
  message: HiChatBubbleLeftRight,
  security: HiShieldCheck,
  key: HiKey,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  java: FaJava,
  spring: SiSpringboot,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  postgresql: SiPostgresql,
  react: SiReact,
  typescript: SiTypescript,
  gitlab: SiGitlab,
  prometheus: SiPrometheus,
  grafana: SiGrafana,
  linux: SiLinux,
  nodejs: SiNodedotjs,
  nestjs: SiNestjs,
  mongodb: SiMongodb,
  redis: SiRedis,
  oracle: SiOracle,
  keycloak: SiKeycloak,
  aws: SiAmazonwebservices,
  python: SiPython,
  bash: SiGnubash,
  sonarqube: SiSonarqube,
  argocd: SiArgo,
  istio: SiIstio,
  helm: SiHelm,
  tailwind: SiTailwindcss,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
